(function(){const c=document.getElementById('particles');const ctx=c.getContext('2d');let W,H,pts=[];function resize(){W=c.width=window.innerWidth;H=c.height=window.innerHeight;}resize();window.addEventListener('resize',resize);for(let i=0;i<70;i++)pts.push({x:Math.random()*2000,y:Math.random()*2000,vx:(Math.random()-.5)*.25,vy:(Math.random()-.5)*.25,r:Math.random()*1.5+.5,o:Math.random()*.4+.1});function draw(){ctx.clearRect(0,0,W,H);pts.forEach(p=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0)p.x=W;if(p.x>W)p.x=0;if(p.y<0)p.y=H;if(p.y>H)p.y=0;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fillStyle=`rgba(255,255,255,${p.o})`;ctx.fill();});requestAnimationFrame(draw);}draw();})();

const cur=document.getElementById('cur'),curf=document.getElementById('curf');
if(cur&&curf&&window.matchMedia('(hover:hover)').matches){let mx=0,my=0,fx=0,fy=0;document.addEventListener('mousemove',e=>{mx=e.clientX;my=e.clientY;cur.style.transform=`translate(${mx-4}px,${my-4}px)`;});(function loop(){fx+=(mx-fx-18)*.11;fy+=(my-fy-18)*.11;curf.style.transform=`translate(${fx}px,${fy}px)`;requestAnimationFrame(loop);})();document.querySelectorAll('a,button,.role-strip,.tc,.f-btn,.ev-row,.team-row').forEach(el=>{el.addEventListener('mouseenter',()=>curf.classList.add('big'));el.addEventListener('mouseleave',()=>curf.classList.remove('big'));});}

const nav=document.getElementById('nav');
window.addEventListener('scroll',()=>{nav.classList.toggle('scrolled',scrollY>60);},{passive:true});

let mobOpen=false;
function toggleMob(){mobOpen=!mobOpen;document.getElementById('mobMenu').classList.toggle('open',mobOpen);document.getElementById('ham').classList.toggle('open',mobOpen);}
function closeMob(){mobOpen=false;document.getElementById('mobMenu').classList.remove('open');document.getElementById('ham').classList.remove('open');}

const rv=document.querySelectorAll('.rv');
const obs=new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');e.target.querySelectorAll('.si-fill').forEach((b,i)=>{setTimeout(()=>{b.style.width=b.dataset.w+'%';},250+i*100);});}});},{threshold:.1});
rv.forEach(el=>obs.observe(el));
document.querySelectorAll('.sg').forEach(g=>{new IntersectionObserver(es=>{if(es[0].isIntersecting)g.querySelectorAll('.si-fill').forEach((b,i)=>setTimeout(()=>{b.style.width=b.dataset.w+'%';},250+i*120));},{threshold:.3}).observe(g);});

function toggleRole(id){const strip=document.getElementById(id);const wasOpen=strip.classList.contains('open');document.querySelectorAll('.role-strip').forEach(s=>s.classList.remove('open'));if(!wasOpen)strip.classList.add('open');}

function filterProj(cat,btn){document.querySelectorAll('.f-btn').forEach(b=>b.classList.remove('on'));btn.classList.add('on');document.querySelectorAll('.ev-row').forEach(p=>{p.classList.toggle('hidden',!(cat==='all'||p.dataset.c===cat));});const teamsBlock=document.getElementById('teamsBlock');if(teamsBlock)teamsBlock.style.display=(cat==='all'||cat==='team')?'':'none';const divider=teamsBlock.previousElementSibling;if(divider)divider.style.display=(cat==='all'||cat==='team')?'':'none';}

document.querySelectorAll('.mag').forEach(btn=>{if(!window.matchMedia('(hover:hover)').matches)return;btn.addEventListener('mousemove',e=>{const r=btn.getBoundingClientRect();const dx=(e.clientX-r.left-r.width/2)*.3;const dy=(e.clientY-r.top-r.height/2)*.3;btn.style.transform=`translate(${dx}px,${dy}px)`;});btn.addEventListener('mouseleave',()=>btn.style.transform='');});

if(window.matchMedia('(hover:hover)').matches){window.addEventListener('scroll',()=>{const y=scrollY;const hl=document.querySelector('.hero-content');const ho=document.querySelector('.hero-object');if(hl)hl.style.transform=`translateY(${y*.07}px)`;if(ho)ho.style.transform=`translateY(${y*.03}px) rotate(${y*.01}deg)`;},{passive:true});}

document.querySelectorAll('.role-strip,.ev-row,.team-row').forEach(card=>{card.addEventListener('touchstart',()=>card.style.opacity='.85',{passive:true});card.addEventListener('touchend',()=>card.style.opacity='',{passive:true});});

(function initSliders(){document.querySelectorAll('[data-slider]').forEach(wrapper=>{const label=wrapper.dataset.label||null;const parent=wrapper.parentElement;const imgs=Array.from(wrapper.querySelectorAll('img'));const ph=wrapper.querySelector('.slide-ph,.photo-placeholder');const sliderEl=document.createElement('div');sliderEl.className='photo-slider'+(imgs.length<=1?' single':'');const track=document.createElement('div');track.className='slides';if(imgs.length===0){const slide=document.createElement('div');slide.className='slide';if(ph)slide.appendChild(ph);track.appendChild(slide);}else{imgs.forEach(img=>{const slide=document.createElement('div');slide.className='slide';slide.appendChild(img);track.appendChild(slide);});}sliderEl.appendChild(track);if(label){const lbl=document.createElement('div');lbl.className='rs-photo-label';lbl.textContent=label;sliderEl.appendChild(lbl);}if(imgs.length>1){const prev=makeArrow('prev','<svg viewBox="0 0 16 16" fill="none"><path d="M10 4L6 8l4 4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>');const next=makeArrow('next','<svg viewBox="0 0 16 16" fill="none"><path d="M6 4l4 4-4 4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>');sliderEl.appendChild(prev);sliderEl.appendChild(next);const dotsEl=document.createElement('div');dotsEl.className='sl-dots';let curIdx=0;const dots=imgs.map((_,i)=>{const d=document.createElement('div');d.className='sl-dot'+(i===0?' on':'');d.onclick=e=>{e.stopPropagation();goTo(i);};dotsEl.appendChild(d);return d;});sliderEl.appendChild(dotsEl);function goTo(n){curIdx=(n+imgs.length)%imgs.length;track.style.transform=`translateX(-${curIdx*100}%)`;dots.forEach((d,i)=>d.classList.toggle('on',i===curIdx));}prev.onclick=e=>{e.stopPropagation();goTo(curIdx-1);};next.onclick=e=>{e.stopPropagation();goTo(curIdx+1);};let tx=0;sliderEl.addEventListener('touchstart',e=>{tx=e.touches[0].clientX;},{passive:true});sliderEl.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-tx;if(Math.abs(dx)>40)goTo(curIdx+(dx<0?1:-1));},{passive:true});}wrapper.replaceWith(sliderEl);});function makeArrow(cls,svg){const btn=document.createElement('button');btn.className='sl-arrow '+cls;btn.innerHTML=svg;btn.type='button';return btn;}})();